config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  
  resources :notes

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]

	def index

		@notes = Note.all.order('created_at DESC')

	end

	def show
	

	end

	def new

		@note = Note.new

	end

	def edit
	

	end

	def create
	
		@note = Note.new(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end

	end

	def update
	

	end

	def destroy
	

	end

	private
	
	def find_note
	
		@note = Note.find(params[:id])

	end

	def note_params
	
		params.require('note').permit(:title, :content )

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.haml
%h1 Welcome to My Notes App

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNotesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!5
%head
	%title My Notes App
	= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	= yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title 
	= f.input :content 
	= f.button :submit

	

app/views/notes/index.html.haml
- @notes.each do |note|
	%h2= note.title
	%p= time_ago_in_words(note.created_at)

app/views/notes/new.html.haml
%h1 New Note 

= render 'form'

app/views/notes/show.html.haml
%h1= @note.title 
%p= @note.content

= link_to 'All Notes', notes_path